Feature/structure
tnyandoro/the-todo-list pull request #1
Opened 2021-07-14 18:43 UTC by tnyandoro

Learning objectives
Use webpack to bundle JavaScript.
Learn how to use proper ES6 syntax.
Use ES6 modules to write modular JavaScript.
Estimated time: 3.5h
Description
In this project, you will build a simple HTML list of To Do tasks. The list will be styled according to the specifications listed later in this lesson. This simple web page will be built using webpack and served by a webpack dev server.

IMPORTANT NOTE: Read all requirements before you start building your project.

General requirements
Make sure that there are no linter errors.
Make sure that you used correct GitHub Flow.
Make sure that you documented your work in a professional way.
HTML/CSS requirements
Follow our list of the best practices for HTML & CSS.
JavaScript requirements
Follow our list of best practices for JavaScript.
Project requirements
Set up a new project with webpack that is based on the webpack exercise you have already completed.
Create an index.html file and write your HTML markup here. Create an empty To-Do List placeholder (<div> or <ul> element). The index.html file must be set as a template using the HTML Webpack Plugin.
Create an index.js file and set an array of some simple to do tasks (array of objects). Each task object should contain three keys:
description [string].
completed [bool].
index: [number].
Write a function to iterate over the tasks array and populate an HTML list item element for each task.
On the page, load render the dynamically created list of tasks in the dedicated placeholder. The list should appear in order of the index values for each task.
Create a style.css and set rules for the To Do List. CS

2021-07-14 19:52 UTC, smcommits requested changes
Hi @tnyandoro, 

### You have done an excellent job. The project appears to be fantastic. It reflects great efforts and good understanding. 
### To make this project even better, there are some issues that you still need to work on. You are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


 ## Required Changes ♻️
_Please check the inline comments below._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-14 19:52 UTC, smcommits commented on src/index.js
> +let todoItems = [];
- [ ] **In this milestone of the project, you are required to create an array containing simple to-do tasks. Please implement it.**

You have to create an array of some simple to-do tasks (array of objects) with each object containing three keys - description [string], completed [bool], index: [number]. However, you are free to have more properties or name them differently. 

Please make sure to dynamically append the predefined tasks into DOM.

2021-07-14 19:52 UTC, smcommits commented on package.json
> +    "start": "webpack serve --open",
- [ ] **When I run this script, the HTML document is not loaded. Please fix this**

Upon running `npm run start` I am getting a black document with no elements. For some reason, your HTML document is not loaded. Please fix this.

2021-07-15 08:30 UTC, tnyandoro commented
in this milestone of the project, you are required to create an array containing simple to-do tasks. Implemented,
When I run this script, the HTML document is not loaded. Please fixed

2021-07-15 09:01 UTC, carlos-ssh requested changes
Hi @tnyandoro , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 09:01 UTC, carlos-ssh commented on dist/index.html
> +<script defer src="main.js"></script></head>
- Kindly add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

2021-07-15 09:48 UTC, tnyandoro commented
Added the Readme

2021-07-15 09:51 UTC, carlos-ssh approved these changes
Hi @tnyandoro , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-15 09:57 UTC, merged